name: Update Allowlist Rules
on:
  schedule:
  - cron: "0 3 */3 * *"
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  run:
    name: Cloudflare Gateway
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
      WHITELIST_URLS: ${{ vars.WHITELIST_URLS }}
      DYNAMIC_WHITELIST: ${{ vars.DYNAMIC_WHITELIST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          
      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11
        
      - name: Cache Data
        id: cache-cloudflare
        uses: actions/cache@main
        with:
          path: cloudflare_cache.json
          key: ${{ runner.os }}-cloudflare-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cloudflare-cache-
      
      # - name: Delete lists
      #   run: python -m src leave
      
      - name: Create lists
        run: python -m src run